# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    param_fetcher_listener:  true
    allowed_methods_listener:  true
    body_listener: true
    access_denied_listener:
        json: true
    routing_loader:
      default_format: json
      include_format: false
    view:
        view_response_listener:  true
        formats:
            json: true
    format_listener:
        rules:
            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
